const { jsPDF } = require('jspdf');
const fs = require('fs');

const doc = new jsPDF();

// PDF Generation Script for Presentation Guide
doc.setFontSize(22);
doc.setTextColor(14, 165, 233); // SaaS Blue
doc.text('CRM Checklist Tool: Presentation Guide', 14, 25);

doc.setFontSize(12);
doc.setTextColor(100);
doc.text('A tool for standardizing workflows and preventing recurring issues.', 14, 35);

doc.setDrawColor(226, 232, 240);
doc.line(14, 40, 196, 40);

doc.setFontSize(16);
doc.setTextColor(15, 23, 42); // Darker Blue/Black
doc.text('1. Why we built this (Preventing Recurring Issues)', 14, 55);

doc.setFontSize(11);
doc.setTextColor(71, 85, 105);
const block1 = [
    'Recurring issues happen because of manual errors or forgotten steps.',
    'This tool creates a standard checklist that every team member must follow.',
    'It calculates "Gaps" between tasks to ensure we never send reminders too fast or too slow.',
    'It provides a professional audit trail via PDF reports for every campaign.'
];
doc.text(block1, 14, 65);

doc.setFontSize(16);
doc.setTextColor(15, 23, 42);
doc.text('2. Key Features to Highlight', 14, 105);

doc.setFontSize(11);
doc.setTextColor(71, 85, 105);
const block2 = [
    '- Batch Management: Group tasks by campaign names.',
    '- Intelligent Timing: Automatic hour gap calculation between activities.',
    '- Progress Tracking: Visual bars showing how close we are to 100%.',
    '- Professional Export: One-click PDF for management reports.',
    '- Data Security: Build-in backup system to save and restore all data.'
];
doc.text(block2, 14, 115);

doc.setFontSize(16);
doc.setTextColor(15, 23, 42);
doc.text('3. How to Demo (The Workflow)', 14, 155);

doc.setFontSize(11);
doc.setTextColor(71, 85, 105);
const block3 = [
    '1. Start: Name your batch (e.g., "April Market Prep") and click Save.',
    '2. Build: Add tasks with date and time. Watch the "Gap" calculate automatically.',
    '3. Execute: Check off tasks as you finish them. Watch the progress bar.',
    '4. Document: Click Export PDF to generate the official campaign report.'
];
doc.text(block3, 14, 165);

doc.setTextColor(14, 165, 233);
doc.setFontSize(10);
doc.text('Report generated by CRM Toolkit - Developed by You & Paul', 14, 280);

const data = doc.output();
fs.writeFileSync('CRM_Presentation_Guide.pdf', data, 'binary');
console.log('PDF saved as CRM_Presentation_Guide.pdf');
